class CreateClippingVariants < ActiveRecord::Migration[8.1]
  # A clipping is a story; each language edition of that story is a variant. The
  # variant holds everything that is language-specific — URL, title and summary —
  # so a bilingual article can point each reader at the edition in their own
  # language. `origin` marks whether the content was written by a person or
  # generated by the model, which is what protects a manual edition from being
  # overwritten by a summary run.
  def change
    create_table :clipping_variants do |t|
      t.references :clipping, null: false, foreign_key: true
      t.string :locale
      t.string :url, null: false
      t.string :title, null: false
      t.text :summary
      t.string :origin, null: false, default: "generated"

      t.timestamps
    end

    add_index :clipping_variants, [ :clipping_id, :locale ], unique: true
    # The source edition is created before the article's language is known, so its
    # locale is NULL until the summary detects it: at most one of those per story.
    add_index :clipping_variants, :clipping_id, unique: true, where: "locale IS NULL",
              name: "index_clipping_variants_on_unsourced_locale"
  end
end
