# Session-based authentication, generated by `bin/rails generate authentication`
# and then trimmed: the `before_action :require_authentication` is deliberately
# not applied globally. It is opted into by Admin::BaseController, so the public
# site (pages, subscriptions, unsubscribe, preferences) stays open without every
# public controller having to opt out.
module Authentication
  extend ActiveSupport::Concern

  included do
    helper_method :authenticated?
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to login_path
    end

    # Built from the main app's routes on purpose: inside the mounted Mission
    # Control engine a host helper would pick up the engine's script_name and
    # redirect to /admin/jobs/login instead of /login.
    def login_path
      Rails.application.routes.url_helpers.new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      resume_session&.destroy
      cookies.delete(:session_id)
    end
end
